### PR TITLE
Improved READMEs

### PR DESCRIPTION
**Pull request by blackcat-917**
Hi, I corrected some things in READMEs

## Changelog

- Added a "translations" header on each readme.
- Updated all README with the latest languages
- Fixed Images broken links (Added the https link to English README to prevent the creation of other broken links)
- Very little changes in the Italian translation

### CODE REVIEW

**Comment by bee-san** [comment]
Oh god this must have taken you forever

**Review by bee-san — APPROVED** [review]

**Comment by bee-san** [comment]
@all-contributors please add @blackcat-917 for documentation

**Comment by bee-san** [comment]
Hey we're changing from MIT to GPLv3 because some of our projects are licensed with that, do you approve? If you do not approve we will be forced to delete your code and rewrite it 😢 

By approving of this change, you are agreeing to re-license the code you wrote under GPLv3.

**Comment by blackcat-917** [comment]
Approved at https://github.com/Ciphey/Ciphey/pull/479

**Pull request merged**
