### PR TITLE
added DNA decoder

### PR DESCRIPTION
**Pull request by anantverma275**
Hi,
I have added the logical code to decode DNA sequence into binary, but for some reason, it's not working with ciphey. 
It shows - "Failed to crack".

The print statement on line #13 was just an attempt to solve the bug, but couldn't. 

Can you help me with this?

### CODE REVIEW

**Comment by bee-san** [comment]
@all-contributors add @anantverma275 for code

**Comment by bee-san** [comment]
@all-contributors please add @anantverma275 for code

**Comment by bee-san** [comment]
@all-contributors please add @anantverma275 for code and bugs

**Comment by Cyclic3** [comment]
I'll take a look at this. Thanks for the code!

**Comment by Cyclic3** [comment]
It appears that you had swapped the `replace` arguments around, ending up encoding the string, rather than decoding it! I've pushed the fix

**Comment by Cyclic3** [comment]
There still appears to be some errors with the decoding, but it's going through your decoder now. Can you fix the rest?

**Comment by anantverma275** [comment]
Yeah, I'll take a look at it.
Thanks.

**Comment by anantverma275** [comment]
Hi, I worked out the logical issue that the decoder in converting 'binary' to 'A/T/G/C' equivalent. But for some reason, again, it's not working with ciphey. Could you help me with this?

**Comment by SkeletalDemise** [comment]
This is being closed because it is not needed, and @anantverma275 agreed on Discord. I'm making a new PR with my DNA codon decoder.

**Pull request closed without merging**
