### PR TITLE
fix can't exit ciphey

### PR DESCRIPTION
**Pull request by e1fy**
so i wasn't able to exit ciphey chika was hawing the same problem

Screenshot_2020-11-02_04-39-32

and even tho it was saying it stopped it really didn't here are screenshots of ps

Screenshot_2020-11-02_04-38-34
Screenshot_2020-11-02_04-39-14

the only thing that could stop it at that point was SIGKILL so i added keyboard interupt exception

### CODE REVIEW

**Comment by bee-san** [comment]
This is failing all of our tests, mind fixing that Elf? :)

**Comment by e1fy** [comment]
> This is failing all of our tests, mind fixing that Elf? :)

idk how i can share screen that it works and how i did it tho

**Review by bee-san — APPROVED** [review]

**Comment by bee-san** [comment]
@all-contributors please add @e1fy for code 🧝

**Comment by bee-san** [comment]
Hey we're changing from MIT to GPLv3 because some of our projects are licensed with that, do you approve? If you do not approve we will be forced to delete your code and rewrite it 😢 

By approving of this change, you are agreeing to re-license the code you wrote under GPLv3.

**Pull request merged**
