### PR TITLE
Add MacPorts Installation Guide

### PR DESCRIPTION
**Pull request by harens**
Closes https://github.com/Ciphey/Ciphey/issues/583

Naturally, since the MacPorts image isn't in the master branch of Ciphey yet, the link for the image will not work. However, you can see what it would look like [here](https://github.com/harens/Ciphey/blob/test-macports/README.md).

image

Since this is IMO the best workaround for macOS (no slowdown compared to Docker), it might be useful to also add this to the [Docs](https://github.com/Ciphey/Ciphey/wiki/Installation). I can't edit it, so maybe something like the following? (based on Docker instructions)

---
### MacPorts

[Click here for how to install MacPorts](https://www.macports.org/install.php).

```
sudo port install ciphey
```

Our [MacPorts port](https://ports.macports.org/port/ciphey/summary) is maintained by @harens.

---

It might also be useful to add MacPorts to the [I can't install Ciphey on Mac OS](https://github.com/Ciphey/Ciphey/wiki/Common-Issues-&-Their-Solutions#i-cant-install-ciphey-on-mac-os) section since this is also a viable workaround. Thanks.

### CODE REVIEW

**Review by bee-san — APPROVED** [review]

**Comment by bee-san** [comment]
How's this in the wiki? :D 

https://github.com/Ciphey/Ciphey/wiki/Common-Issues-&-Their-Solutions#i-cant-install-ciphey-on-mac-os

**Comment by harens** [comment]
It looks great 👍 Thanks @bee-san.

**Comment by bee-san** [comment]
Hey we're changing from MIT to GPLv3 because some of our projects are licensed with that, do you approve? If you do not approve we will be forced to delete your code and rewrite it 😢 

By approving of this change, you are agreeing to re-license the code you wrote under GPLv3.

**Comment by harens** [comment]
Not that I wrote any code...but I'm more than happy with the transition :)

**Pull request merged**
