### PR TITLE
Add Chinese translation

### PR DESCRIPTION
**Pull request by chuinzer**
the docs are ready just finished translating it

### CODE REVIEW

**Comment by bee-san** [comment]
Hey! You changed the english readme & contributing files themselves. Can you copy the chinese versions to:
https://github.com/Ciphey/Ciphey/tree/master/translations

Change the old verions back to English, and in the English readme add a flag + language here? :D 
image

**Comment by chuinzer** [comment]
oh ok

**Comment by SkeletalDemise** [comment]
Hey @chuinzer, I fixed it for you. I changed the main readme and contributing files back to English, and added a flag and language code to the readme. Can you translate the Code of Conduct file (https://github.com/Ciphey/Ciphey/blob/master/CODE_OF_CONDUCT.md) to Chinese too? We'll still merge the pull request even if you don't, but it would be nice. Thank you!

**Comment by chuinzer** [comment]
sorry i was busy with my homework , I will do that now

**Comment by chuinzer** [comment]
done. sorry for the long delay.

**Comment by SkeletalDemise** [comment]
@all-contributors please add @chuinzer for language translation

**Review by SkeletalDemise — APPROVED** [review]

**Comment by imba-tjd** [comment]
机翻也太严重了吧……虽然有总比没有好咯

**Pull request merged**
