### PR TITLE
Add Soundex Cracker

### PR DESCRIPTION
**Pull request by sashreek1**
Hey! I have written the necessary scripts to add in the new feature - soundex crcaker

this solves #412

### CODE REVIEW

**Comment by SkeletalDemise** [comment]
@all-contributors please add @sashreek1 for code

**Comment by SkeletalDemise** [comment]
@all-contributors please add @sashreek1 for code

**Review by SkeletalDemise — APPROVED** [review]

**Comment by bee-san** [comment]
Hey we're changing from MIT to GPLv3 because some of our projects are licensed with that, do you approve? If you do not approve we will be forced to delete your code and rewrite it 😢 

By approving of this change, you are agreeing to re-license the code you wrote under GPLv3.

**Comment by sashreek1** [comment]
I approve the change, seems all good to me!

**Pull request merged**
