### PR TITLE
Support Python 3.9 (Fix #558)

### LINKED ISSUE #558: Ciphey TypeError with Python 3.9
**⚠️IMPORTANT⚠️ if you do not fill this out, we will automatically delete your issue. We will not help anyone that cannot fill out this template.**

- [x] Have you read our [Wiki page "Common Issues & Their Solutions"?](https://github.com/Ciphey/Ciphey/wiki/Common-Issues-&-Their-Solutions)

**Describe the bug**
After installing Ciphey using pip3, running Ciphey with any argument will cause the problem.

**Plaintext**
**⚠️IMPORTANT⚠️ The below code is non-negotiable for "Ciphey didn't decrypt...." problems. If you do not tell us your plaintext, we will not help you.** 

```
raceback (most recent call last):
  File "<home>/.local/bin/ciphey", line 5, in <module>
    from ciphey.ciphey import main
  File "<home>/.local/lib/python3.9/site-packages/ciphey/__init__.py", line 1, in <module>
    from . import basemods, common, iface
  File "<home>/.local/lib/python3.9/site-packages/ciphey/basemods/__init__.py", line 1, in <module>
    from . import Checkers, Crackers, Decoders, Resources, Searchers
  File "<home>/.local/lib/python3.9/site-packages/ciphey/basemods/Checkers/__init__.py", line 1, in <module>
    from . import any, brandon, ezcheck, format, human, quorum, regex
  File "<home>/.local/lib/python3.9/site-packages/ciphey/basemods/Checkers/any.py", line 3, in <module>
    from ciphey.iface import Config, ParamSpec, PolymorphicChecker, registry
  File "<home>/.local/lib/python3.9/site-packages/ciphey/iface/__init__.py", line 1, in <module>
    from ._config import Config
  File "<home>/.local/lib/python3.9/site-packages/ciphey/iface/_config.py", line 11, in <module>
    from ._modules import PolymorphicChecker, ResourceLoader, Searcher
  File "<home>/.local/lib/python3.9/site-packages/ciphey/iface/_modules.py", line 208, in <module>
    class CrackResult(NamedTuple, Generic[T]):
  File "/usr/lib/python3.9/typing.py", line 1820, in _namedtuple_mro_entries
    raise TypeError("Multiple inheritance with NamedTuple is not supported")
TypeError: Multiple inheritance with NamedTuple is not supported
```
**Version**
**⚠️IMPORTANT⚠️ We need this information because different environments will induce different bugs in Ciphey**
 - OS/Distro: Arch Linux
 - Python version: Python 3.9.0
 - Ciphey versions: ciphey 5.11.0, cipheycore 0.3.2, cipherdists 0.3.34
 - Did you use Docker? No

**Verbose Output**
**⚠️IMPORTANT⚠️ Verbose output will tell us why it's not working the way we expected it to be.**
Run Ciphey with `ciphey -vvv` and paste the results into [Pastebin.com](https://pastebin.com) or a [GitHub Gist](https://gist.github.com/)

Verbose output is the same as the plaintext.

**To Reproduce**
1. What input did you use? Any input or without input.
2. What flags / arguments did you use? Any argument or without argument

**Expected behavior**
Ciphey runs without this error.

**Any other information?**

### PR DESCRIPTION
**Pull request by JesseEmond**
This issue was already raised on https://bugs.python.org/issue36517,
adding a TODO to consider going back to Generic[T] once this is solved.

Tested `python -m ciphey -t "aGVsbG8gbXkgbmFtZSBpcyBiZWU="` on Python 3.9, and it works with this fix.

### CODE REVIEW

**Comment by JesseEmond** [comment]
Should I include a change to https://github.com/Ciphey/Ciphey/blob/master/.github/workflows/terminaltest.yml#L10 to include 3.9 as part of this PR?

**Comment by bee-san** [comment]
Hey!

Thanks for this <3 

Do you mind editing our tests to include pythobn 3.9?

https://github.com/Ciphey/Ciphey/blob/master/.github/workflows/tests2.yml

^ I think that's what we use for CI, but the name is quite bad haha

**Comment by bee-san** [comment]
Hey!

This fails on Windows, which is okay -- it's not your fault.

We're removing CipheyCore so Windows will work in the future. For now, Linux & Mac OS support on 3.9 is great 🥳 

I think we're going to take this & intentionally fail our CI until we can add support for Windows when we remove CipheyCore.

Thanks so much!

@all-contributors please add @JesseEmond for code

**Review by SkeletalDemise — APPROVED** [review]

**Comment by SkeletalDemise** [comment]
@all-contributors please add @JesseEmond for code

**Comment by bee-san** [comment]
Hey we're changing from MIT to GPLv3 because some of our projects are licensed with that, do you approve? If you do not approve we will be forced to delete your code and rewrite it 😢 

By approving of this change, you are agreeing to re-license the code you wrote under GPLv3.

**Pull request merged**
