### PR TITLE
Added an Indonesian Translation for the README.md file

### PR DESCRIPTION
**Pull request by Bryzizzle**
I've added a translated version of the `README.md` file into the `translations/id/` directory.
Additionally, I've also added some MacOS specific `.gitignore` definitions, you may remove them if you'd rather not have them.

_This would actually be my first time doing something like this (this is actually my first pull-request on GitHub. ever.), so please kindly tell me if I did something wrong in the process. Thanks!_

### CODE REVIEW

**Comment by brandonskerritt** [comment]
Hey!

Nice, congrats on your first PR :D 

In case you didn't know, we run continuous integration to test whether or not you've accidentally broken the program (see "All checks have passed") and every PR (including from me) must be code reviewed :) 

Let me just check out what you've done before taking the PR

**Comment by brandonskerritt** [comment]
@all-contributors please add @Bryzizzle  for language, translation, documentation (its one of those lol)

**Comment by Bryzizzle** [comment]
@brandonskerritt Thankss, I really do hope there aren't any mistakes in the translation :). I'll go ahead and continue to translate the other markdown docs soon and I hope that these translations are of great help to you!

**Comment by brandonskerritt** [comment]
> @brandonskerritt Thankss, I really do hope there aren't any mistakes in the translation :). I'll go ahead and continue to translate the other markdown docs soon and I hope that these translations are of great help to you!

You're now on the GitHub readme by the way :)

**Comment by bee-san** [comment]
Hey we're changing from MIT to GPLv3 because some of our projects are licensed with that, do you approve? If you do not approve we will be forced to delete your code and rewrite it 😢 

By approving of this change, you are agreeing to re-license the code you wrote under GPLv3.

**Pull request merged**
