### PR TITLE
add french translation of the README file

### PR DESCRIPTION
**Pull request by yafkari**
Simply adds french translation for the README file.

Will try to translate CODE_OF_CONDUCT.md and CONTRIBUTING.md when I will have more time ^^

### CODE REVIEW

**Comment by bee-san** [comment]
@all-contributors please add @yafkari for translation language :)

**Review by bee-san — APPROVED** [review]

**Comment by bee-san** [comment]
@yafkari You need to link in the original README english file:
image
Like this :)

**Comment by bee-san** [comment]
Hey, you have git conflicts. Please solve them :)

**Comment by bee-san** [comment]
Hey we're changing from MIT to GPLv3 because some of our projects are licensed with that, do you approve? If you do not approve we will be forced to delete your code and rewrite it 😢 

By approving of this change, you are agreeing to re-license the code you wrote under GPLv3.

**Comment by yafkari** [comment]
I approve.

**Pull request merged**
