### PR TITLE
Added italian translation

### PR DESCRIPTION
**Pull request by blackcat-917**

### CODE REVIEW

**Comment by Albertosaurusrex** [comment]
I'll pick up the slack from this here; 

The changes made is a new folder for italian .md files, where an empty README.md, CODE_OF_CONDUCT.md and CONTRIBUTING.md 

I assume that @blackcat-917 will make another PR for the content?

**Comment by blackcat-917** [comment]
> I'll pick up the slack from this here;
> 
> The changes made is a new folder for Italian .md files, where an empty README.md, CODE_OF_CONDUCT.md and CONTRIBUTING.md
> 
> I assume that @blackcat-917 will make another PR for the content?

I'm writing that translation, I'll commit the translation when it's ready to merge and convert this pull request to "ready for review"

**Review by bee-san — APPROVED** [review]

**Comment by bee-san** [comment]
@all-contributors please add @blackcat-917 for language or translation

**Comment by bee-san** [comment]
Hey we're changing from MIT to GPLv3 because some of our projects are licensed with that, do you approve? If you do not approve we will be forced to delete your code and rewrite it 😢 

By approving of this change, you are agreeing to re-license the code you wrote under GPLv3.

**Comment by blackcat-917** [comment]
@bee-san yes, I approve

**Pull request merged**
