### PR TITLE
Add Tap Code Decoder

### LINKED ISSUE #337: Add support for Prisoner's Tap Code
Hello spoooopyyy hackers :jack_o_lantern: 

This is a Hacktoberfest only issue! :ghost: 

Find our contributing guidelines here, this walks you through how to add a decoder / cracker! 
https://github.com/Ciphey/Ciphey/wiki#adding-your-own-crackers--decoders

Don't worry if it looks hard, we will walk you through everything! :) 

**Write this issue in Python!**

# Links
These links will help you understand how this works!

https://en.wikipedia.org/wiki/Tap_code

### PR DESCRIPTION
**Pull request by Itamai**
i also made a pull request for ciphedists to add the translation for the tap code.
the letter "K" is not supported and is at the current state not possible to implement that but everything else works fine
closes #337

### CODE REVIEW

**Comment by bee-san** [comment]
Can you merge with master? I updated it to feature newest cipheydists :)

**Comment by Itamai** [comment]
> Can you merge with master? I updated it to feature newest cipheydists :)

merged it to the latest version. All checks passed :)

**Comment by bee-san** [comment]
Thanks so much! Can I just say how much we appreciate this. You've contributed 2 amazing PRs so far! Outstanding work. You even fixed bugs we couldn't fix 😉

**Comment by bee-san** [comment]
Hey we're changing from MIT to GPLv3 because some of our projects are licensed with that, do you approve? If you do not approve we will be forced to delete your code and rewrite it 😢 

By approving of this change, you are agreeing to re-license the code you wrote under GPLv3.

**Comment by Itamai** [comment]
> Hey we're changing from MIT to GPLv3 because some of our projects are licensed with that, do you approve? If you do not approve we will be forced to delete your code and rewrite it 😢
> 
> By approving of this change, you are agreeing to re-license the code you wrote under GPLv3.

I approve the license change you can use my code :)

**Pull request merged**
