### PR TITLE
Fix grammatical errors

### PR DESCRIPTION
**Pull request by androiddevnotes**
Motivation: To improve readability

Solution: Fix grammatical errors

### CODE REVIEW

**Review by bee-san — APPROVED** [review]

**Comment by bee-san** [comment]
Hey, I can't merge your PR. GitHub says your branch is out of date with the base branch :(

**Comment by bee-san** [comment]
Closing due to inactivity :( Please open up another PR if you want, sorry :heart:

**Comment by bee-san** [comment]
Hey we're changing from MIT to GPLv3 because some of our projects are licensed with that, do you approve? If you do not approve we will be forced to delete your code and rewrite it 😢 

By approving of this change, you are agreeing to re-license the code you wrote under GPLv3.

**Comment by androiddevnotes** [comment]
@bee-san Hey, sorry for the late reply. That's cool, approved.

**Pull request closed without merging**
