### PR TITLE
Added translation Thai language

### PR DESCRIPTION
**Pull request by PunGrumpy**
@bee-san, I will update the Thai language to improve the documents:

- `README.md`
- `CONTRIBUTING.md`
- `CODE_OF_CONDUCT.md`

### CODE REVIEW

**Review by yimmee123 — APPROVED** [review]
Thk

**Review by PunGrumpy — COMMENTED** [review]
thx

**Comment by SkeletalDemise** [comment]
Thank you. :+1:

**Comment by PunGrumpy** [comment]
you're welcome. 😄

**Pull request merged**
